# Generated by Django 4.0.4 on 2022-06-08 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('pontos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='O que deseja saber?', max_length=20)),
                ('nome_autor', models.CharField(max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField()),
                ('docente_teorica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor')),
                ('docentes_praticas', models.ForeignKey(default='nome', on_delete=django.db.models.deletion.CASCADE, related_name='cadeiras', to='portfolio.professor')),
                ('linguagens', models.ForeignKey(default='linguagens', on_delete=django.db.models.deletion.CASCADE, to='portfolio.linguagem')),
                ('projetos', models.ForeignKey(default='projetos', on_delete=django.db.models.deletion.CASCADE, to='portfolio.projeto')),
            ],
        ),
    ]
