# Generated by Django 4.0.4 on 2022-06-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='ects',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
