# Generated by Django 4.0.4 on 2022-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_pontuacaoquizz_alter_post_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontuacaoquizz',
            name='pontos',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
