# Generated by Django 4.0.4 on 2022-06-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_projeto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='ranking',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
