# Generated by Django 4.0.5 on 2022-06-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
