# Generated by Django 4.0.5 on 2022-06-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_projeto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, upload_to='image')),
                ('relatorio', models.CharField(max_length=300)),
                ('link_github', models.TextField()),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor')),
            ],
        ),
    ]
