# Generated by Django 4.0.5 on 2022-06-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_tfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='link_github',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='relatorio',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
