# Generated by Django 4.0.5 on 2022-06-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_tfc_link_github_alter_tfc_relatorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfc',
            name='autor',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
